import Head from "next/head";
import Avatar from "../components/Avatar";
import Image from "next/image";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;
    else {
      router.push(`/search?term=${term}`);
    }
  };

  return (
    <div className="flex flex-col justify-center h-screen items-center">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://img.icons8.com/color/2x/google-logo.png"
        />
      </Head>
      <header className="flex w-full  p-3 justify-between text-sm text-gray-700">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">images</p>
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          //<Avatar url="https://media-exp1.licdn.com/dms/image/C4D03AQH34EFzopClig/profile-displayphoto-shrink_800_800/0/1642782924048?e=1666828800&v=beta&t=dKXOjVNAcvJcPAu25MagIn7k3YFusb__rInl5rAY6pU" />
        </div>
      </header>
      <form className="flex flex-col items-center flex-grow mt-36 w-4/5">
        <Image
          src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          height={100}
          width={300}
        />
        <div className="h-10 flex w-full mt-5 hover:shadow-md focus-within:shadow-md max-w-md rounded-full border border-gray-200 items-center px-5 py-3 sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchInputRef}
            type="text"
            className="flex-grow focus:outline-none "
          />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={search} className="btn">
            Google Search
          </button>
          <button onClick={search} className="btn">
            I&apos;m Feeling Lucky
          </button>
        </div>
      </form>
      <Footer />
    </div>
  );
}
